"use strict";
'use es6';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CONTACT_ASSOCIATED = exports.INPUT_STAGING = exports.UNREAD_CONVERSATION_COUNT_CHANGED = exports.CONVERSATION_CLOSED = exports.CONVERSATION_STARTED = void 0;
const CONVERSATION_STARTED = 'conversationStarted';
exports.CONVERSATION_STARTED = CONVERSATION_STARTED;
const CONVERSATION_CLOSED = 'conversationClosed';
exports.CONVERSATION_CLOSED = CONVERSATION_CLOSED;
const UNREAD_CONVERSATION_COUNT_CHANGED = 'unreadConversationCountChanged';
exports.UNREAD_CONVERSATION_COUNT_CHANGED = UNREAD_CONVERSATION_COUNT_CHANGED;
const INPUT_STAGING = 'inputStaging';
exports.INPUT_STAGING = INPUT_STAGING;
const CONTACT_ASSOCIATED = 'contactAssociated';
exports.CONTACT_ASSOCIATED = CONTACT_ASSOCIATED;