import { ZERO_ONE_ADDRESS } from 'constants/index'
import { ChainId } from 'constants/sdk-extra'

export const FLAGCORE_ADDRESSES: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: ZERO_ONE_ADDRESS,
  [ChainId.ROPSTEN]: ZERO_ONE_ADDRESS,
  [ChainId.RINKEBY]: ZERO_ONE_ADDRESS,
  [ChainId.GÖRLI]: ZERO_ONE_ADDRESS,
  [ChainId.KOVAN]: ZERO_ONE_ADDRESS,
  [ChainId.BSC_MAINNET]: ZERO_ONE_ADDRESS,
  [ChainId.BSC_TESTNET]: ZERO_ONE_ADDRESS,
  [ChainId.AVALANCHE_C_CHAIN]: ZERO_ONE_ADDRESS,
  [ChainId.AVALANCE_FUJI_TESTNET]: ZERO_ONE_ADDRESS,
  [ChainId.DFK_MAINNET]: '0x659D6F1Ba11c388A55091dc83e77808081201D5D',
  [ChainId.DFK_TESTNET]: '0xfD892302248D97626bF61Ea5C4308cFaF2b4dA1C',
  [ChainId.HARMONY_MAINNET]: '0x284F756A212Afd072E5a6033Ace9BE0Eed1d8811',
  [ChainId.HARMONY_TESTNET]: '0x2e0B652a5BBc6547DD11aA7A25235dd92d2Fde23',
  [ChainId.HARDHAT]: ZERO_ONE_ADDRESS
}

// FLAG STORAGE IDs
export const HERO_VISUAL_MOD_STORAGE_ID = 1
export const HERO_ACHIEVEMENT_STORAGE_ID = 4
export const HERO_JOURNEY_STORAGE_ID = 5

export const WALLET_ACHIEVEMENT_STORAGE_ID = 2

// FLAG STORAGE ELEMENTS
export const HERO_VISUAL_MOD_ELEMENT_INDEX = 0
export const HERO_ACHIEVEMENT_ELEMENT_INDEX = 0
export const HERO_JOURNEY_ELEMENT_INDEX = 0

export const WALLET_ACHIEVEMENT_ELEMENT_INDEX = 0

// FLAG STORAGE BIT INDICES
export const HERO_VISUAL_MOD_CASUALTY_BIT_INDEX = 0
export const HERO_VISUAL_MOD_SURVIVOR_BIT_INDEX = 1

export const HERO_ACHIEVEMENT_SURVIVOR_BIT_INDEX = 0

export const HERO_JOURNEY_SURVIVOR_BIT_INDEX = 0
export const HERO_JOURNEY_CASUALTY_BIT_INDEX = 1

export const HERO_JOURNEY_STAT_UP_ELIGIBLE_BIT_INDEX = 2
export const HERO_JOURNEY_STAT_UP_USED_BIT_INDEX = 3
