import { ZERO_ONE_ADDRESS } from 'constants/index'
import { ChainId } from 'constants/sdk-extra'
import miningScene from 'assets/images/professions/quest-mining.gif'
import { Quest } from '../Quest'
import { QuestKeys, QuestProviderKeys, QuestType, Professions } from '../types'

export const goldMiningLevel0 = new Quest({
  key: QuestKeys.GOLD_MINING_0,
  title: 'Gold Mining',
  addresses: {
    [ChainId.MAINNET]: ZERO_ONE_ADDRESS,
    [ChainId.ROPSTEN]: ZERO_ONE_ADDRESS,
    [ChainId.RINKEBY]: ZERO_ONE_ADDRESS,
    [ChainId.GÖRLI]: ZERO_ONE_ADDRESS,
    [ChainId.KOVAN]: ZERO_ONE_ADDRESS,
    [ChainId.BSC_MAINNET]: ZERO_ONE_ADDRESS,
    [ChainId.BSC_TESTNET]: ZERO_ONE_ADDRESS,
    [ChainId.AVALANCHE_C_CHAIN]: ZERO_ONE_ADDRESS,
    [ChainId.AVALANCE_FUJI_TESTNET]: ZERO_ONE_ADDRESS,
    [ChainId.DFK_MAINNET]: ZERO_ONE_ADDRESS,
    [ChainId.DFK_TESTNET]: ZERO_ONE_ADDRESS,
    [ChainId.HARMONY_MAINNET]: '0x569E6a4c2e3aF31B337Be00657B4C040C828Dd73',
    [ChainId.HARMONY_TESTNET]: '0x029ca80AB56491Bf239197242E39cA0B49f76F15',
    [ChainId.HARDHAT]: ZERO_ONE_ADDRESS
  },
  provider: QuestProviderKeys.QUARRYSMITH_GREN,
  type: QuestType.TimeBased,
  level: 0,
  duration: 20,
  baseStaminaCost: 1,
  proficientStaminaCost: 1,
  baseDuration: 12,
  proficientDuration: 10,
  proficiencyType: Professions.MINING,
  minHeroes: 1,
  maxHeroes: 6,
  startQuestName: 'Gold mining',
  tooltipText:
    '<p><strong>Gold Mining Quests</strong> can be performed by a group of anywhere between 1 and 6 Heroes at a time. Heroes can be queued to begin questing as soon as the Stamina of the currently questing Heroes is expended; however, the group of Heroes will all stop mining as soon as any Hero’s Stamina reaches zero. Additionally, once a group of any size enters the mine, additional miners cannot be added to the group. Those Heroes will be queued and will not commence their quest until one Hero in the previous group reaches 0 Stamina, causing the entire group to stop mining.</p><p>The amount of gold generated by a miner is based on each Hero’s STR and END scores, mining score and on whether the Hero has mining as their main profession. Each Hero calculates rewards separately, even when questing as a group.</p><p>Heroes with mining as their main profession expend 1 Stamina every 10 minutes, and all other Heroes expend 1 Stamina per 12 minutes. However, if a group of Miners contains Heroes that do not have mining as their main profession, all Heroes in that group will expend at the 1 Stamina per 12 minutes rate. It is important to strategically group miners to achieve maximum rewards.</p><p>Mining quests also have a chance to reward Heroes with Gaia’s Tears, Shvās runes, and Yellow Eggs. Item drop rates are increased by varying combinations of STR, END, the mining stat, and the mining gene.</p>',
  rewardsDialogueMap: {
    noRewardMessage:
      'Hard luck, coming back from a day of digging, covered with soot and nothing to show for it but calloused hands and a weary body.',
    questFailedMessage:
      'Hard luck, coming back from a day of digging, covered with soot and nothing to show for it but calloused hands and a weary body.',
    tearsComboMessage:
      'Even more beautiful than gold and Jewels! More Tears mean more Heroes, and that’s always a good thing!',
    runesComboMessage:
      'Look at it pulsating! That humming reminds me of the sound of my pickaxe chipping away at a solid piece of ore.',
    tearsOrRunesOnlyMessage: 'It’s not ore exactly but might be even more valuable.',
    eggMessage:
      'Well well, looks like you dug up an egg. That’s a great find, but be careful. No one really knows what sort of creatures live down in those mines.'
  },
  prompts: [
    'All that glitters is not gold, but I’ll show you how to tell the difference.',
    'Grab your pickaxe and let’s get mining!',
    'There’s a rich vein in there just waiting for you. Come on!'
  ],
  location: 'Professions',
  locationUrl: 'professions',
  sceneImage: miningScene,
  audio: 'https://defi-kingdoms.b-cdn.net/game-audio/fx/sfx_quest_mining.ogg'
})
